### ISSUE TITLE
No JS Search

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#41] opened 2022-05-14 11:48 UTC
Currently the only javascript is the search. For all reasons, this is basically a non-issue. It works perfectly.

But how great would it be to actually say with certainty - "Abridge has **no** JavaScript."

I'm wondering how difficult it would be to change this to use Web-Assembly/Rust. For now, this will likely be an outstanding issue, but I just want to track it for now.

**Comment by Jieiku** [comment] 2022-05-14 15:05
There are two search engines that I am aware of that do this, [stork](https://github.com/jameslittle230/stork) and [tinysearch](https://github.com/mre/tinysearch)

I posted to zola github here: https://github.com/getzola/zola/issues/1849

The problem is that Stork and Tinysearch do not work as well with CJK/stemmers/stopwords

Stork: https://github.com/jameslittle230/stork/issues/293

TinySearch: https://github.com/tinysearch/tinysearch/issues/157

elasticlunr-rs: https://github.com/mattico/elasticlunr-rs/issues/43

I love the idea myself as well, and technically Stork or Tinysearch could be implemented in this theme even without them being merged into Zola, but we would need to build the search index ourselves.

**Comment by simbleau** [comment] 2022-05-14 15:25
It would be something Abridge has that no one else has, which makes me enthusiastic about the idea. I'll try to look into it with some help, but I have no guarantee on timeline. Could be weeks.

**Comment by Jieiku** [comment] 2022-05-14 15:31
Yes I agree, I also edited my previous post to include information about how you can reduce the two js files into a single js file.

**Comment by Jieiku** [comment] 2022-06-09 19:35
After a bit more thought, I would only want to implement stork or tinysearch if we can submit the part that generates the index to the zola code base, otherwise people that depend on remote build tools such as netlify build action, would not be able to use these other searches.

If we could add the index generation as an additional option for zola and submit it as a pull request to the zola project then I think it would be good to add stork and tinysearch support.

**Comment by Jieiku** [comment] 2022-08-04 03:12
I did a little work integrating tinysearch, but I am not sure yet how to retrieve the body of the post:  https://github.com/tinysearch/tinysearch/issues/159

**Comment by Jieiku** [comment] 2022-08-05 02:27
I have stork partially implemented, it works but the styling is all off, I have to fix it similarly to how I did for tinysearch.

tinysearch came in at half the size of elasticlunr, but stork on the other hand came in at 3 time larger.

Unless stork brings something significant to the table then I don't really see any reason to use it over elasticlunr or tinysearch.

I am going to finish the implementation because it will be interesting to fully benchmark all 3 on a larger data set.

![2022-08-04_19-25-05](https://user-images.githubusercontent.com/106644/182988329-bd2a7b1e-262d-4313-863b-c53dbe3725e2.png)

**Comment by simbleau** [comment] 2022-08-05 03:34
Awesome work!

**Comment by Jieiku** [comment] 2022-08-07 20:12
Still need to add a meta field to tinysearch, but both Stork and Tinysearch are implemented.

Stork does not return a results page when you press enter or the search icon, it uses typescript instead of vanilla javascript so it is a whole lot less hackable, not that its impossible, just takes more work. The suggestions popup does function though and results are clickable.

I also updated the readme to outline how to switch to these alternate searches.

Stork demo: https://jieiku.github.io/abridge-stork/

Tinysearch demo: https://jieiku.github.io/abridge-tinysearch/

**Comment by egrieco** [comment] 2022-08-09 05:36
For sake of completeness, have you looked at?

* [pagefind](https://github.com/cloudcannon/pagefind) (Rust): Static low-bandwidth search at scale
* [lyra](https://github.com/nearform/lyra) (TypeScript): Fast, in-memory, typo-tolerant, full-text search engine written in TypeScript.

This issue seems to have the best list of Static Site Generator search options that I've found. I'm tending toward a Rust based solution, at least for search. With regard to SSGs, I'm working on transitioning all of my sites from Middleman and Zola over to [soupault](https://soupault.app/). Soupault's model is just so much more flexible.

**Comment by Jieiku** [comment] 2022-08-14 20:40
I did take a quick look at soupault, it is not written in rust so I decided not to look further. I really want to become proficient with rust over time, so I am trying to make use of rust as much as I can.

I have a very good understanding of the necessary workaround to make use of zola so its few shortcomings are not an issue for me (but I can totally see how it can be an issue for newcomers to zola or abridge).

pagefind, the only demo I could find of it in use was here: https://pagefind.app/
it seems which you click into the search it initially loads this:

![2022-08-14_13-27-49](https://user-images.githubusercontent.com/106644/184553742-b32eb760-a54a-4bd4-a572-c9e357f6d75c.png)

It seems to then download chunks for the results as you type, I can see how this would save a LOT of bandwidth 

![2022-08-14_13-30-17](https://user-images.githubusercontent.com/106644/184553816-ba76a5d8-7ba6-4cef-847d-5461303f24eb.png)

lyra, the demo seems to download a 7MB file which considering the index is apparently 37,000 items is probably impressive, but the pagefind engine seems more interesting.

Thanks for the info. I have bookmarked these things. I may try integrating pagefind!

**Comment by Jieiku** [comment] 2022-08-14 20:43
The initial implementation of this is complete.

Stork demo: https://jieiku.github.io/abridge-stork/

Tinysearch demo: https://jieiku.github.io/abridge-tinysearch/

**Closed by Jieiku** 2022-08-14 20:43 UTC

**Comment by simbleau** [comment] 2022-08-14 20:55
Woah, it's done?

**Comment by Jieiku** [comment] 2022-08-14 20:58
yes, I also updated the readme, feel free to try out the demo links. I may implement pagefind later, it certainly looks interesting.
