### ISSUE TITLE
Add support for additional fonts

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#17] opened 2022-05-06 12:21 UTC

**Comment by Jieiku** [comment] 2022-05-06 14:17
This is outside the goal of abridge which is to be lightweight and fast.

I will however add to the readme to outline how somebody can add additional fonts if they want.

I will add this information to the readme shortly today.

**Comment by simbleau** [comment] 2022-05-06 14:18
Awesome, thanks!

**Comment by Jieiku** [comment] 2022-05-06 23:11
Just added this. note the extra config.toml settings:

```toml
[extra]
# ...
# For externally loaded fonts make sure the include the FULL url including the http/https prefix
fonts_load = false
fonts = [
    {url = "https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700|Source+Code+Pro"},
    {url = "https://fonts.googleapis.com/css?family=Merriweather:300,400|Montserrat:400,700"},
    {url = "FiraCode-Bold.woff2"},
    {url = "FiraCode-Regular.woff2"},
]
```

**Comment by eugenesvk** [comment] 2023-04-30 13:34
Is it possible to make the sass files use a variable with "!default" so that I can change your font list on import instead of having to edit the theme files directly?

**Comment by Jieiku** [comment] 2023-04-30 16:52
Actually you can override any of the sass files, I am planning to add this to the documentation.

This link may help: https://github.com/getzola/zola/issues/2124

I will write something up with a more clear example though, incase its not clear. In your case you would only need to override the _auto.scss file in your base site sass folder.

**Comment by Jieiku** [comment] 2023-04-30 17:44
Ah, seems not having that breaks even overrides in the base site, I will add this asap to both the base theme and the refactor branch, as well as some of the other variables.

**Comment by eugenesvk** [comment] 2023-04-30 17:53
Thanks for the links, I've read them and use (though afaik it's better to use `@use` than `@import` per sass docs), but then it doesn't work properly for non-vars/mixins/functions, that is, for actual styles like `root` with the `font-family`, so even if I import your theme file as a module (`@use "../../themes/abridge/sass/_variables.scss" as abridge-var`) and then add my own family to root, I'll have two styles in the output, the original from import and my override (though in this case I don't understand the need for an import, I can just include the font-family string style directly and it will override your theme)

With a variable I could append my couple of fallback fonts to the end of your existing variable string (actually, not sure `!default` helps here as then I'd have to supply the whole list myself, but I can do `module_name.$font_fam_var : string.insert(module_name.$font_fam_var, " my_fallback_font", -1)
And this 
  - better shows intent (I don't want to change all the fonts, just add an extra symbol fallback font)
  - allows picking up whatever changes you make in the future theme versions since I'm not overwriting everything
  - does not duplicate styles in the output

**Comment by Jieiku** [comment] 2023-04-30 18:03
> but I can do `module_name.$font_fam_var : string.insert(module_name.$font_fam_var, " my_fallback_font", -1)

oh, that is a nifty trick! I would like to try that and also add that to the documentation.

**Comment by Jieiku** [comment] 2023-04-30 18:18
When I change this in Abridge, it affects running the theme directly.

Here is the theme without !default, you can see that the font matches:

![2023-04-30_11-13-39](https://user-images.githubusercontent.com/106644/235369484-a4e63a66-ce9d-4323-8d89-47e4e44049b4.png)


If I add !default to the Abridge theme --ff variable:

```
:root {
  --ff: "Roboto", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", "Noto Sans", Helvetica, Arial, sans-serif !default;
```

Once I add !default this happens to the theme, as you can see it is no longer using the intended Roboto font:

![2023-04-30_11-15-46](https://user-images.githubusercontent.com/106644/235369608-f40a9492-805c-4b0b-897e-6a72153cb01b.png)

So I am not sure if we can add !default to that, unless I can find a way that does not negatively affect the base theme.

**Comment by Jieiku** [comment] 2023-04-30 18:25
I am trying to remember my reason for using a css variable instead of a sass variable. I assume that is the reason I am unable to add !default without affecting base theme font. Let me do a few tests real quick.

**Comment by Jieiku** [comment] 2023-04-30 18:50
I think my only reason for using a css vairable `--ff` instead of a sass variable `$ff` was because sass variables can only be used within their scope.

At the time I was trying to define the font family within the vars file, I think one way to do this is to just set the sass variable in the` _document.scss` file.

Have you tried making any of these changes yet locally?

**Comment by eugenesvk** [comment] 2023-04-30 18:55
But it's not a sass variable, so you can't add `!default` there, I think it needs to be
```sass
$font-family-main : "Roboto", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", "Noto Sans", Helvetica, Arial, sans-serif !default
:root
  --ff: #{$font-family-main}  /* though you lose quotes here, which are important for fonts with numbers :((( */
```

So this would work unless fonts had numbers in them (like `Noto Sans Symbols 2` fails, needs `"Noto Sans Symbols 2"`, while regular fonts don't really need to be quoted)
Oh, well, strange sass interpolation rules kill this feature for this specific property

**Comment by Jieiku** [comment] 2023-04-30 18:58
ahhh I see what you did there, so it is still a css variable, but you set it using a sass variable.

Strange nobody has address the shortcoming of that font with numbers issue.... how common are fonts with numbers I wonder...

**Comment by eugenesvk** [comment] 2023-04-30 18:59
> Have you tried making any of these changes yet locally? I am assuming when you asked for a variable, you meant a sass variable instead of a css variable.

Yes, I meant sass variables
I'm using them for dynamic color schemes within your theme, that's where you need a combo of both css vars and sass vars (sass vars allow using colors defined in some other sass modules, while css vars are used by your theme to set the switching dynamic)

```sass
:root.light
  --f1   	: #{var(--gray12)}	/* gray12 comes from another color theme */
  --tt-bg	: #{sol.$bg_l}    	/* $bg_l is from my local theme module file, but could also be an override from importing your theme files */
```

**Comment by Jieiku** [comment] 2023-04-30 19:02
Are you currently running the master branch of abridge or the refactor branch?

In the refactor branch I switched to using mixins for the colors.

**Comment by eugenesvk** [comment] 2023-04-30 19:17
> Strange nobody has address the shortcoming of that font with numbers issue

well, not really strange, these js/browser thingies are full of broken holes here and there that don't get fixed for years

> how common are fonts with numbers I wonder

Not sure, but unfortunatly am using one, so my suggestion wouldn't help myself :( Or maybe it would, afaik you don't really need the css var as he font family is not dynamically changed with anything, right? So then I could just import your var, append it and use directly in
```css
html {
  font-family: var(--ff);
}
```

> Are you currently running the master branch of abridge or the refactor branch?

the master branch, saw the refactor efforts, tried it, but if I remember correctly would've needed to change a bit more than I liked at the time, so will wait till the new version is released

> In the refactor branch I switched to using mixins for the colors.

nice, everything should be vars/functions/mixins so it can be adjused :)

(though I think it should be `@use` everywhere since it provides better encapsulation etc. https://sass-lang.com/documentation/at-rules/use#differences-from-import and `@import` is being phased out)

**Comment by Jieiku** [comment] 2023-04-30 19:22
I had considered using use for the color mixing, but apparently it cannot be nested in style rules, so I am not sure I would have made that work. There are probably a lot of other places I could be making use of `@use` though, so I will certainly add that to my todo list.

Also that is correct, the -ff variable simple gets set and applied to the html element, it never changes:

```bash
grep --color -i --binary-files=without-match --include=\* -rnw "/home/jieiku/.dev/abridge" -e "ff"

/home/jieiku/.dev/abridge/sass/include/_document.scss:28:  font-family: var(--ff);
/home/jieiku/.dev/abridge/sass/_variables.scss:117:  --ff: "Roboto", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", "Noto Sans", Helvetica, Arial, sans-serif;
```

**Comment by eugenesvk** [comment] 2023-04-30 19:43
> it cannot be nested in style rules, so I am not sure how I would have made that work

you can nest it with https://sass-lang.com/documentation/modules/meta#load-css (this has the nice feature of allowing to set names dynamically, not that it's a good idea :)), but the proper way from my shallow understanding is to group styles into mixins and then `@include` those in whatever nests you like by `@include <namespace>.<mixin>()`

**Comment by eugenesvk** [comment] 2023-05-01 05:41
I think I might have found a workaround for the quotation weirdness! You can use `"'nested quotes'"` to remove only the outer layer
```sass
@use "sass:string"
@use "sass:list"
@use "sass:meta"
// ↓ imported from your library
$mysassvar : "'Roboto'", "'Segoe UI'", "'Helvetica Neue'", sans-serif
// ↓ added in user code
$myextrafontlist: ("'my font 1'", "'my font 2'")
@debug $mysassvar
// ↓ or reverse order to prepend your fonts
$mysassvar : list.join($mysassvar, $myextrafontlist)
@debug $mysassvar

// ↓ only the "outer" quotes removed, 'inner' remain
.style
  --mycssvar : #{$mysassvar}

```

gets
```css
.style {
  --mycssvar: 'Roboto', 'Segoe UI', 'Helvetica Neue', sans-serif, 'my font 1', 'my font 2';
}
```

**Comment by Jieiku** [comment] 2023-05-01 05:50
Nice, I started switching over to use instead of import, will give this a try very soon and implement it if I don't spot any issues.

**Comment by eugenesvk** [comment] 2023-05-01 06:28
Also found this trick in sass issues
> or you can use interpolation in the property name so that Sass's special custom property parsing behavior (which is necessary for CSS compatibility) doesn't activate:
```sas
$font-family: "Font with Spaces and 33", serif
:root
  #{--font-family}: $font-family
```

**Comment by Jieiku** [comment] 2023-05-01 16:15
Awesome, that looks like a much cleaner solution.

**Comment by eugenesvk** [comment] 2023-05-01 16:20
Yeah, and you can use regular `//comments`  in this format instead of the `/* loud ones */` within regular `--cssvars`!

**Comment by Jieiku** [comment] 2023-05-01 16:28
I only use a handful of loud comments, usually at the top of files, are you proposing doing something different with those?

https://github.com/Jieiku/abridge/blob/75bb461162f7644a498101bc121faac3cfee7799/sass/include/_icons.scss#L1-L11

**Comment by eugenesvk** [comment] 2023-05-01 16:33
Wasn't proposing anything re. your code, if you think those need to be present in the output, that's fine.

I was just mentioning a benefit of the other notation since I got cut by the fact that css vars don't support regular comments and was wondering why the styles wouldn't apply...

**Comment by Jieiku** [comment] 2023-05-01 22:11
I merged your pull request, I also replaced all occurrences of import with use, except for the ones that involve the color mixins that I use, need to think about the cleanest way to do that.

**Comment by eugenesvk** [comment] 2023-05-02 05:49
The variables still define rules directly, so the `abridge-var.$font` trick doesn't yet work:

```sass
// userMainCustomFile.sass
@use "_variables" as abridge-var with ($font:("RobotoWith"))

abridge-var.$font : "RobotoVarOverride"
// ↑ this fails without a mixin, the output still be :root {--ff: "RobotoWith";}
// ↓ but if _variables didn't have rules directly, but instead encapsulated them in a mixin
@include abridge-var.all-rules
// ↑ this would output: :root {--ff: "RobotoVarOverride";}
```

```scss
// abridge's _variables.sass
$font: "RobotoOriginal" !default

// ↓1 currently, no mixin
:root
  #{--ff}: $font // ← this can only be overriden with `@use "_variables" with($font:"RobotoWith")`
// but then you can't append anything, only replace

// ↓2 bright future, mixin, can dynamically update with `abridge-var.$font`
@mixin all-rules
  :root // side note: though if it's a mixin, maybe it should not have a selector and let the caller set it?
    #{--ff}: $font
```

**Comment by eugenesvk** [comment] 2023-05-02 06:56
> I merged your pull request, I also replaced all occurrences of import with use, except for the ones that involve the color mixins that I use, need to think about the cleanest way to do that.

I think the color mixins just need to use `@forward`
```sass
// imports.sass
@forward "colors/orange" as theme-*
```

and then you can use it like so:
```sass
// abridge.sass
@use "imports" as i
:root.light
  @include i.theme-light
```

Although trying to use `@forward` lead to grass sass compiler panicking, not sure what's going on there, that's up to grass/zola

**Comment by Jieiku** [comment] 2023-05-02 16:23
I am seeing the same problem.

I am going to setup a VERY simple test case for this in a repo and open an issue at the grass repository. it appears in zola's cargo.lock file that they are using the latest grass crate, also this version should support `@forward` so I am not sure what the problem is.

https://github.com/getzola/zola/blob/2b56bcb967cb7284e3225fc5caac50b095185004/Cargo.lock#L1191-L1198

**Comment by eugenesvk** [comment] 2023-05-02 16:39
wanted to post it in the other issue you opened, but that was deleted too quickly :)

FYI this is the appending function I use
```sass
// file: _function.sass
@use "sass:meta"
@use "sass:list"

@function append-font($base, $ext, $font-sep)
  $base-pre	: ()
  $base-pos	: ()
  $iFontSep : index($base, $font-sep)
  @if not $iFontSep // didn't find the font separator, return
    @return $base

  @for $i from 1 through list.length($base)
    $iEl: list.nth($base, $i)
    @if $i <= $iFontSep
      $base-pre: list.append($base-pre, $iEl, $separator:comma)
    @else
      $base-pos: list.append($base-pos, $iEl, $separator:comma)

  @return list.join(list.join($base-pre, $ext), $base-pos)
```

and how you could use it in the main file
```sass
// file: main.sass
@use "../path/to/../themes/abridge/sass/_variables"	as var
@use "function"                                    	as f
// this appends two fonts after Segoe UI in the main font family and Segoe UI Mono in the code font family
$iSegoe-Main     	: index(var.$font     , "Segoe UI"     ) // find index within existing variable
$iSegoe-Code     	: index(var.$font-mono, "Segoe UI Mono")
$font-ext-symbols	: ("Noto Sans Symbols 2", "Noto Sans Symbols") // fonts to append
@if $iSegoe-Main // if font not found, silently do nothing
  var.$font      : f.append-font(var.$font     , $font-ext-symbols, "Segoe UI"     )
@if $iSegoe-Code
  var.$font-mono : f.append-font(var.$font-mono, $font-ext-symbols, "Segoe UI Mono")
```

**Comment by eugenesvk** [comment] 2023-05-02 16:41
According to this grass issue https://github.com/connorskees/grass/issues/19 forward is indeed supposed to be supported

**Comment by Jieiku** [comment] 2023-05-02 16:43
yep I am going to setup a barebones repo of a zola theme for them to test this. It will basically be a single page with a couple sass files, something much simpler than abridge that easily identifies the problem.

**Comment by Jieiku** [comment] 2023-05-02 17:14
LOL! and this is why you make simple test cases, my simple test case the feature works without issue:

```bash
git clone https://github.com/Jieiku/zola-grass-forward-test
cd zola-grass-forward-test
cd fails-with-forward
zola serve
```

Now we have to figure out why

**Comment by Jieiku** [comment] 2023-05-02 17:28
I think I know the problem... one sec.

**Comment by eugenesvk** [comment] 2023-05-02 17:51
it was due to the imports at dark/light themes, for example
```scss
//abridge-dark.scss
// panic
@import "imports";
@import "syntax/syntax-abridge-dark";

:root {
  @include dark;
}

// no panic
@use "imports"                   	as i;
@use "syntax/syntax-abridge-dark"	as syntax;

:root {
  @include i.dark;
}
```

**Comment by Jieiku** [comment] 2023-05-02 17:52
so it was simply that all 4 needed to be switched over at once, I had wondered that.

**Comment by eugenesvk** [comment] 2023-05-02 18:05
yeah, and if you switch them to mixins, you could have all the syntax colors defined in one file in two light/dark mixins and then just use the relevant one in the abridge-light/dark/auto file

**Comment by Jieiku** [comment] 2023-05-02 18:09
The colors currently are set to mixins:

https://github.com/Jieiku/abridge/blob/294044d3225f93244ec6096921a655b4bbbdb97d/sass/colors/_orange.scss#L1

so I am assuming you mean something different?

**Comment by Jieiku** [comment] 2023-05-02 18:12
ahhh yes, your absolutely right, that would be a good idea.

**Comment by eugenesvk** [comment] 2023-05-02 18:39
> swapping out syntect eventually

ah, ok (though I dislike TextMate grammar mentioned there as a potential replacement, Sublime's is much more ergonomic)

Re the fonts - what did you have in mind re. adding it for everyone, 
  - would users edit some sass script directly in your theme or 
  - copy&paste an example to their main file and tweak it there?

I'm going down the 2nd route (and actually disable loading the theme's files in with `stylesheets  	= [ ]` to avoid having duplication in the theme's file and my overrides), so in that sense the function is tested and does add those two fonts to the mix

(and zola doesn't expose any config vars in the sass processing, right?, so the users can't set extra font family names in the config, there are no sass tera templates?)

**Comment by Jieiku** [comment] 2023-05-02 18:49
2nd route sounds perfect

That is correct you cannot tera template a sass file. I am actually trying to extend zola's ability to template additional files, at the moment js and json files, but i am still very new to rust:

https://github.com/Jieiku/zola/tree/file-templates

`https://github.com/getzola/zola/issues/2167`

**Comment by Jieiku** [comment] 2023-05-03 07:35
Just finished the Mixins for the syntax, also add a variable to _variables.scss to disable loading the syntax

**Comment by Jieiku** [comment] 2023-05-11 08:29
I spent a bit of time trying to cleanup the syntax mixin to use variables:

https://github.com/Jieiku/abridge/issues/117

**Closed by Jieiku** 2023-05-11 08:29 UTC
