### ISSUE TITLE
setting minify_html breaks page formatting on pages with numbered code blocks

### ISSUE THREAD

**Issue by skewballfox** [Jieiku/abridge#84] opened 2022-07-20 18:37 UTC
I'm not sure if this is a bug or not, but currently setting `minify_html=true` causes the table of contents to be rendered at the bottom of the post(after go to top) rather than the side.

**Comment by simbleau** [comment] 2022-07-24 22:54
Issue is getting stale. @skewballfox Are you still having issues?

**Comment by skewballfox** [comment] 2022-07-25 01:04
yes, unless it's something specific to my system I'm pretty sure you can test this yourself.
```sh
git clone https://github.com/Jieiku/abridge
cd abridge
sed -i 's/minify_html = false/minify_html = true/g' config.toml
zola serve --port 1234
```
then navigate to [the local copy of the code blocks entry](http://127.0.0.1:1234/overview-code-blocks/), and you should see a missing  Index box, which is now improperly renderered after the body of the post

**Comment by simbleau** [comment] 2022-07-25 01:10
Thanks, will look into this.

**Comment by Jieiku** [comment] 2022-07-25 01:46
@skewballfox Thanks! I just followed your example to the letter.

here is Firefox:
![2022-07-24_18-45-45](https://user-images.githubusercontent.com/106644/180677525-f574dcf1-8973-4666-b1a6-1e148fb8cca1.png)

here is chrome:
![2022-07-24_18-46-34](https://user-images.githubusercontent.com/106644/180677576-6ace690a-7c6e-4a24-8c34-9b48ee43d625.png)

What Operating System, Browser, and resolution are you using?

**Comment by skewballfox** [comment] 2022-07-25 02:57
not quite, I'm talking about the page **Code blocks and themes**, not the index/list of post. I was using that specific post as an example, but the issue will be present for any post which has multiple headings

![image](https://user-images.githubusercontent.com/29311431/180686957-af047b10-ae72-45e8-a17e-cb37f63722f6.png)
here is the table of contents for that page rendered below the post when minified. it's correct when not minified though

I've used firefox and chrome on fedora 36, resolution should be 1080p

**Comment by Jieiku** [comment] 2022-07-25 03:33
Perfect, I see the issue as well. This is a new issue, I am able to reproduce this and will figure out the cause.

**Comment by Jieiku** [comment] 2022-07-25 17:51
I was able to reproduce this with another theme, so it does not appear to be abridge specific: https://github.com/Jieiku/zola-minify-test

**Comment by Jieiku** [comment] 2022-08-09 03:29
Closing because it is unrelated to Abridge, for now I simply disabled the minify_html option.

**Closed by Jieiku** 2022-08-09 03:29 UTC
